name: Create release Tags
on: workflow_dispatch
#inputs:
#      name:
#        description: 'Person to greet'
#        required: true
#        default: 'Mona the Octocat'
#      home:
#        description: 'location'
#        required: false
#        default: 'The Octoverse'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Ec-tests-stack to run the smoke tests
        uses: actions/checkout@v2
        with:
          repository: cebroker/ec-tests-stack
          token: ${{ secrets.GitHub_PAT }}
          path: ec-tests-stack
      - name: Set up node environment
        uses: actions/setup-node@v2
        with:
          node-version: '13.8.0'
      - name: Test everything so far is working
        run: |
          node -v
          pwd
      - name: Run the smoke tests
        run:
      - name: Bump version and push tag
        uses: actions/checkout@v2
        id: tag_version
        uses: mathieudutour/github-tag-action@v5.6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}
